version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
    run:
      - name: test
      - command: echo test

  test_for_prd:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
    run:
      - name: test_for_prd
      - command: echo test_for_prd

  deploy:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
    run:
      - name: deplooy
      - command: echo deplooy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - test_for_prd:
          filters:
            tags:
              only: /^v(\d\.){2}\d.*/
            branches:
              ignore: /.*/
      - approval:
          type: approval
      -deploy:
          requires:
            - approval
          filters:
            tags:
              only: /^v(\d\.){2}\d.*/
            branches:
              ignore: /.*/
