version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: build
          command: echo build

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: test
          command: echo test

  test_for_prd:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: test_for_prd
          command: echo test_for_prd

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deplooy
          command: echo deplooy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      # ブランチpush＋指定したtagsで発火
      - build:
          filters:
            tags:
              only: /^v(\d\.){2}\d.*/

      # ブランチpushのみ発火
      - test:
          requires:
            - build

      # 指定したtagsでのみ発火
      - test_for_prd:
          requires:
            - build
          filters:
            tags:
              only: /^v(\d\.){2}\d.*/
            branches:
              ignore: /.*/

      # 指定したtagsでのみ発火（コマンドは実行しない）
      - approval:
          type: approval
          requires:
            - build
          filters:
            tags:
              only: /^v(\d\.){2}\d.*/
            branches:
              ignore: /.*/

      # 指定したtagsでのみ発火（approval後）
      - deploy:
          requires:
            - approval
